# CMake generated Testfile for 
# Source directory: C:/projects/faocas_qc_w/lpng
# Build directory: C:/projects/faocas_qc_w/lpng/build_release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(pngtest "./pngtest" "C:/projects/faocas_qc_w/lpng/pngtest.png")
ADD_TEST(pngvalid "./pngvalid")
ADD_TEST(pngstest "./pngstest" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn0g01.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn0g02.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn0g04.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn0g08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn0g16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn2c08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn2c16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn3p01.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn3p02.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn3p04.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn3p08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn4a08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn4a16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn6a08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/basn6a16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbbn0g01.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbbn0g02.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbbn0g04.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbbn2c16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbbn3p08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbgn2c16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbgn3p08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbrn2c08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbwn0g16.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbwn3p08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftbyn3p08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftp0n0g08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftp0n2c08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftp0n3p08.png" "C:/projects/faocas_qc_w/lpng/contrib/pngsuite/ftp1n3p08.png")
